// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220823093043_SeedMoreProducts")]
    partial class SeedMoreProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEcommerce.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Книги",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Фильмы",
                            Url = "movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Видеоигры",
                            Url = "video-games"
                        });
                });

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Научно-популярная книга американского программиста Чарльза Петцольда, в которой рассказывается, как персональные компьютеры работают на аппаратном и программном уровне.",
                            ImageUrl = "https://libroroom.ru/upload/iblock/833/18804.png",
                            Price = 1630m,
                            Title = "Код. Тайный язык информатики"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Эта книга посвящена хорошему программированию. Она полна реальных примеров кода. Мы будем рассматривать код с различных направлений: сверху вниз, снизу вверх и даже изнутри. Прочитав книгу, вы узнаете много нового о коде. Более того, вы научитесь отличать хороший код от плохого. Вы узнаете, как писать хороший код и как преобразовать плохой код в хороший.",
                            ImageUrl = "https://cdn1.ozone.ru/multimedia/wc1000/1023228489.jpg",
                            Price = 780m,
                            Title = "Чистый код. Создание, анализ и рефакторинг"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Паттерны проектирования остаются важным инструментом в арсенале разработчика, поскольку они опираются на фундаментальные принципы проектирования. Тем не менее, появление новых конструкций в современных языках программирования делает одни паттерны более важными, а значимость других сводит к минимуму.",
                            ImageUrl = "https://cdn1.ozone.ru/multimedia/wc1000/1012077651.jpg",
                            Price = 630m,
                            Title = "Паттерны проектирования на платформе .NET"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Земля, пережившая войну с инопланетными захватчиками, опустела; остатки человечества готовятся покинуть непригодную для жизни планету. Главный герой — техник по обслуживанию дронов — находит разбившийся корабль NASA, команда которого погибает у него на глазах. Ему удаётся спасти лишь одну женщину — и вскоре он понимает, что это перевернёт его жизнь.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/ru/4/48/Oblivion_2013.jpg",
                            Price = 920m,
                            Title = "Обливион"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "В ближайшем будущем разнообразные технологии участвуют во всех аспектах человеческой жизни. Но в этом технологичном мире Грей — один из немногих людей, кто любит работать руками. Он восстанавливает и чинит старые автомобили. Однажды, возвращаясь от клиента, Грей с женой попадают в аварию, а после — в руки банды отморозков, в результате чего женщина погибает, а Грей оказывается парализованным ниже шеи. Тот самый богатый клиент предлагает несчастному поставить экспериментальный имплант Stem, который может полностью восстановить подвижность.",
                            ImageUrl = "https://www.megacritic.ru/media/reviews/photos/original/ef/a0/f3/1009784-50-1540074712.jpg",
                            Price = 740m,
                            Title = "Апгрейд"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Негодяи, подонки, вконец обнаглевшие и распоясавшиеся преступники и бандитские группировки всё равно не желают сдавать свои упрочившие позиции, опасаясь лишь одного - встречи с легендарным Судьёй Дреддом, пересажавшим или расстрелявшим не одну сотню насильников, террористов и жадных до человеческих страданий маньяков. В то время, как беспорядки и бесчинства бушуют на улицах города, Дредд спешит вернуть порядок, Закон и тишину, которым, кажется, уже никогда не обрести свою былую полноту, мощь и силу...",
                            ImageUrl = "https://www.megacritic.ru/media/reviews/photos/original/f1/f9/ef/_kinopoisk.ru-dredd-3d-1942523-1344945818.jpg",
                            Price = 0m,
                            Title = "Судья Дредд"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Артур Морган и другие подручные Датча ван дер Линде вынуждены пуститься в бега. Их банде предстоит участвовать в кражах, грабежах и перестрелках в самом сердце Америки. За ними по пятам идут федеральные агенты и лучшие в стране охотники за головами, а саму банду разрывают внутренние противоречия. Артуру предстоит выбрать, что для него важнее: его собственные идеалы или же верность людям, которые его взрастили.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/ru/0/03/Red_Dead_Redemption_2_coverart.jpg",
                            Price = 2300m,
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Cyberpunk 2077 — приключенческая ролевая игра с открытым миром, рассказывающая о киберпанке-наёмнике Ви и борьбе за жизнь в мегаполисе Найт-Сити. Мрачное будущее стало ещё более впечатляющим в улучшенной версии, в которую вошли новые дополнительные материалы. Создайте персонажа, выберите стиль игры и начните свой путь к высшей лиге, выполняя заказы, улучшая репутацию и оттачивая навыки. Ваши поступки влияют на происходящее и на весь город. В нём рождаются легенды. Какую сложат о вас?",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/ru/b/bb/%D0%9E%D0%B1%D0%BB%D0%BE%D0%B6%D0%BA%D0%B0_%D0%BA%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BD%D0%BE%D0%B9_%D0%B8%D0%B3%D1%80%D1%8B_Cyberpunk_2077.jpg",
                            Price = 1200m,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Таинственное событие, известное как Death Stranding, в будущем открыло дверь между миром живых и миром мертвых. Как результат, уродливые потусторонние твари отправились бродить по падшему миру, в котором почти не осталось людей. Действуя от лица Сэма Бриджеса и объединяя последних выживших на территории Америки, вам предстоит возродить надежду человечества. Удастся ли вам шаг за шагом воссоединить разрушенный мир?",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/ru/e/ee/Death_Stranding_Poster.jpg",
                            Price = 1750m,
                            Title = "Death Stranding"
                        });
                });

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.HasOne("BlazorEcommerce.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
